version: '1'

tasks:
  fulcro:
    cmds:
      - asciidoctor -o DevelopersGuide.html -b html5 -r asciidoctor-diagram -r ./register-fulcro-examples.rb DevelopersGuide.adoc
  gist:
    cmds:
      - asciidoctor -o DevelopersGuide.html -b html5 -r asciidoctor-diagram -r ./register-gist-macro.rb DevelopersGuide.adoc

