version: '1'

tasks:
  expand: # this results in the generation of the expanded DevelopersGuide as a side-effect of running the ruby extension 
    cmds: 
      - asciidoctor  -r ./register-fulcro-examples.rb DevelopersGuideSource.adoc
      - rm -rf DevelopersGuideSource.html
  book:
    cmds:
      - asciidoctor -o DevelopersGuide.html -b html5  -r asciidoctor-diagram DevelopersGuide.adoc

